-- Fix Grade 6 Lesson.videoUrl: clear broken/placeholder IDs from 0011;
-- set Math year-path lessons to oEmbed-verified public YouTube URLs (mostly Khan Academy).
-- Only SET when oEmbed returned 200. Prosper-branded LessonVideo cover unchanged.
-- Do NOT run db:setup.

-- 1) Clear every G6 lesson whose videoUrl contains a known-broken YouTube ID
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%0LplHnPEs_I%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%1A4V2nOQ0pI%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%1xbHSFnDI64%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%24Y8v9xGd0Y%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%37zarVcXRTE%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%3PDnti9X8LR%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%7Lqr9d1m3dE%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%9DxrF6Tt0Aw%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%AfXD9A9v2hM%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%HsXlKBn9M9o%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%J7TqhAVdGXY%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%JnNkFMRWbIM%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%LQG-SXJzP8s%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%LRP8d7R96FY%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%OgSh6XpzqOE%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%OrK9Onk6FfY%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%Ph3SNsxz9fE%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%VgDe_DJbwII%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%a4lVH2YdQnA%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%bqXne-jGJgU%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%bueEeAsyZ6w%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%c4G7XG_zYrE%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%eg591BaGfOw%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%fHIzX0WZJqk%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%guNdty5R0I0%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%kN3YQZQ0H8w%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%kmjf7k3S160%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%o85OkeKw1j0%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%oqMVx6xMqjE%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%qgaSnqkwxLw%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%qhwP2qudC9c%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%s-KvoVzukHo%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%uej-8JLYb4k%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%uenYu1q2YpA%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%yQC56gFhDsQ%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%ytVgcQZ9w5A%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6);

-- 2) Clear Math G6 mismatched working IDs (wrong topic) before remapping
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%2SUvWfNJSsM%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6 AND subject = 'Mathematics');
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%3XOt1fjWKi8%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6 AND subject = 'Mathematics');
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%T5Qf0qSSJFI%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6 AND subject = 'Mathematics');
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%U2ovEuEUxXQ%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6 AND subject = 'Mathematics');
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "videoUrl" LIKE '%qYjiVWwefto%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6 AND subject = 'Mathematics');

-- 3) Clear archived Math stubs (prefer null)
UPDATE "Lesson" SET "videoUrl" = NULL WHERE "title" LIKE '[Archived stub]%' AND "courseId" IN (SELECT id FROM "Course" WHERE grade = 6 AND subject = 'Mathematics');

-- 4) Set Math G6 year-path lessons to verified YouTube URLs
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=bIKmw0aTmYc' WHERE "id" = 'ppg6m905332d7d5edce2a5397';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=4S3Mbl0JrdY' WHERE "id" = 'ppg6mdbf2a1264b34d23c27d3';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=MaMk6-f3T9k' WHERE "id" = 'ppg6m552a25fb0026764b04e9';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=suRIY3ULrQo' WHERE "id" = 'ppg6mb17d9d3e6d765a6605aa';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=UK-_qEDtvYo' WHERE "id" = 'ppg6m58ce71646e98365cbc7c';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=4S3Mbl0JrdY' WHERE "id" = 'ppg6m5802c985106e3c77d660';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=MaMk6-f3T9k' WHERE "id" = 'ppg6m43653926b886ad6e2c3d';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=4S3Mbl0JrdY' WHERE "id" = 'ppg6m86a8c44ded99194d4324';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=bIKmw0aTmYc' WHERE "id" = 'ppg6m940b80d7538891c1577c';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=U2ovEuEUxXQ' WHERE "id" = 'ppg6m03a14da27c6ec1ff23b7';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=52ZlXsFJULI' WHERE "id" = 'ppg6m6373cc09f86ec44f415d';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=x6xtezhuCZ4' WHERE "id" = 'ppg6m9264f3f5e0548beb82bb';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=f3ySpxX9oeM' WHERE "id" = 'ppg6m1a9866035e9ffee533b6';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=f3ySpxX9oeM' WHERE "id" = 'ppg6m1346a92b50b1cb896407';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=xkg7370cpjs' WHERE "id" = 'ppg6me8ff373d3d0a84c1f534';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=wtrrr15mbvQ' WHERE "id" = 'ppg6mc1650dc0c9c50b54e43a';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=oLh_sIESQnY' WHERE "id" = 'ppg6m20fa95db3030c582a2ec';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=JEHejQphIYc' WHERE "id" = 'ppg6mb614de93636ff3a475b0';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=sCVyvfOLI6U' WHERE "id" = 'ppg6mf12b8365acc88a2e9d7e';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=Zm0KaIw-35k' WHERE "id" = 'ppg6mdb21f501137e58a3248c';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=qGTYSAeLTOE' WHERE "id" = 'ppg6me204f7ef1e7ae361078c';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=jOZ98FDyl2E' WHERE "id" = 'ppg6mb6e029ef066c9e42cc35';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=MD5JUwAeg6c' WHERE "id" = 'ppg6m2f00de398fc7a1f106f9';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=-lUEWEEpmIo' WHERE "id" = 'ppg6m65c6412a156ad3fc69a1';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=d1oNF88SAgg' WHERE "id" = 'ppg6mc3762076d75a9ae4bb42';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=d1oNF88SAgg' WHERE "id" = 'ppg6m366e9f8c273bd53dab0f';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=d1oNF88SAgg' WHERE "id" = 'ppg6mb1429ed880c1d6c986cd';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=d1oNF88SAgg' WHERE "id" = 'ppg6m0c13c70041be208a5ed3';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=qGTYSAeLTOE' WHERE "id" = 'ppg6m091444c4041475c9c62c';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=XZRQhkii0h0' WHERE "id" = 'ppg6m4bd9fafd983c3446719e';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=XZRQhkii0h0' WHERE "id" = 'ppg6mf2388d20892a9f7bc49e';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=ClYdw4d4OmA' WHERE "id" = 'ppg6m29c4c4631b0f95037e4a';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=ClYdw4d4OmA' WHERE "id" = 'ppg6mf40debd88876a9170582';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=XZRQhkii0h0' WHERE "id" = 'ppg6mb921df72cf2c9d74affd';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=XZRQhkii0h0' WHERE "id" = 'ppg6m2f4013547a401c793ec1';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=ClYdw4d4OmA' WHERE "id" = 'ppg6m9348b8c9470c58440845';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=ClYdw4d4OmA' WHERE "id" = 'ppg6ma145b53fec88c95f26e1';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=TlZVPfvTLXA' WHERE "id" = 'ppg6m2da5ce75f2249468e4f3';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=zpln5ExhkyI' WHERE "id" = 'ppg6m12b746f7d16798dc93b0';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=TlZVPfvTLXA' WHERE "id" = 'ppg6md01ef2aea19ddca33f3c';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=zpln5ExhkyI' WHERE "id" = 'ppg6m0529e0eac9f4723dcd34';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=TlZVPfvTLXA' WHERE "id" = 'ppg6m663ee54eb7d0f40abe81';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=zpln5ExhkyI' WHERE "id" = 'ppg6me41844ce28e865e2420f';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=pAlq9fFwtus' WHERE "id" = 'ppg6m0664ce63fdb0fa23b713';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=TlZVPfvTLXA' WHERE "id" = 'ppg6m0e99124e71fdafdfe51a';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=zpln5ExhkyI' WHERE "id" = 'ppg6m4b8fbf459d7df425c13f';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=TlZVPfvTLXA' WHERE "id" = 'ppg6m4e8c8e62f95b0b3e4b49';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=tHYis-DP0oU' WHERE "id" = 'ppg6m3a33773b786ac1916dee';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=eFXcsXnKkjw' WHERE "id" = 'ppg6mc3ecef7d65b45f6a411b';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=S_OX3ByvBSc' WHERE "id" = 'ppg6m1a9c8954b78e53243b3b';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=1DgDt6gCUKs' WHERE "id" = 'ppg6m77489dca9fb98eef92a9';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=1DgDt6gCUKs' WHERE "id" = 'ppg6ma53f5c90c81993b98b00';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=Jp25LHI9wII' WHERE "id" = 'ppg6mdf30eab94c13fdfafd13';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=rHNY01R2VSQ' WHERE "id" = 'ppg6m0318d11f0e852d83be91';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=eFXcsXnKkjw' WHERE "id" = 'ppg6m718a5e2ed37022ec76c3';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=eFXcsXnKkjw' WHERE "id" = 'ppg6ma78f87ad965e2dc60064';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=tHYis-DP0oU' WHERE "id" = 'ppg6ma6da85d9265c42b39f2d';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=jWpiMu5LNdg' WHERE "id" = 'ppg6m0c0b35d7e22bbf77d238';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=jWpiMu5LNdg' WHERE "id" = 'ppg6m7b6f039067e575845ca3';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=jWpiMu5LNdg' WHERE "id" = 'ppg6m5525e0fd62c6fb37a2f6';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=jWpiMu5LNdg' WHERE "id" = 'ppg6me935d9263c96bdaf1f0e';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=ilWDSYnTEFs' WHERE "id" = 'ppg6m8bd9ae6f6baf25fbf369';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=ilWDSYnTEFs' WHERE "id" = 'ppg6mdc1303414b425f5ce31b';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=ilWDSYnTEFs' WHERE "id" = 'ppg6m82a4dc0d2c91e52a561b';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=ilWDSYnTEFs' WHERE "id" = 'ppg6m0f492051af75d101d7bb';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=jWpiMu5LNdg' WHERE "id" = 'ppg6m0623b2b9c74beb35714a';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=jWpiMu5LNdg' WHERE "id" = 'ppg6mf4954f28e595448920b1';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=hm17lVaor0Q' WHERE "id" = 'ppg6m6ee0346723044865a8c8';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=hm17lVaor0Q' WHERE "id" = 'ppg6m52705b5ecd9b4a0bf4cc';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=rRTXKQpblEc' WHERE "id" = 'ppg6m7087550782430b112f0d';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=rRTXKQpblEc' WHERE "id" = 'ppg6m908b3758565a96ce2ebe';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=j3-XYLnxJDY' WHERE "id" = 'ppg6m0ae6df4b211402904b25';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=hm17lVaor0Q' WHERE "id" = 'ppg6mace69e232ee8c0c6f8d8';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=pAlq9fFwtus' WHERE "id" = 'ppg6me3259123214f02f847e0';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=5ctsUsvIp8w' WHERE "id" = 'ppg6m0138fd960bd762307913';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=INqaHHZGt8w' WHERE "id" = 'ppg6me06345b63e08242eadae';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=5ctsUsvIp8w' WHERE "id" = 'ppg6m09397d5abb407b02330e';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=5ctsUsvIp8w' WHERE "id" = 'ppg6m88e4bd6991286bf4d150';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=pAlq9fFwtus' WHERE "id" = 'ppg6m2590efebb35ec9d6ab17';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=pAlq9fFwtus' WHERE "id" = 'ppg6mb5451b90490780f01a06';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=pAlq9fFwtus' WHERE "id" = 'ppg6m2a3fe367839fe1dfff68';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=1Pa2GUdKGB0' WHERE "id" = 'ppg6mcf6a3bf283f77ee6d893';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=1Pa2GUdKGB0' WHERE "id" = 'ppg6m9afc3cc6f153e1d58e43';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=mtMNvnm71Z0' WHERE "id" = 'ppg6maff3ce219a86bd886c61';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=m1ZTnl4CNQg' WHERE "id" = 'ppg6m40167e8bbe452abbef29';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=I9efKVtLCf4' WHERE "id" = 'ppg6m8f690218cd5b1c458efb';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=EJTPGyWqhqc' WHERE "id" = 'ppg6m77731119cf4abb32a696';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=I9efKVtLCf4' WHERE "id" = 'ppg6md86ed4bc4b47fcb6672e';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=I9efKVtLCf4' WHERE "id" = 'ppg6m98e42397aa625b8a287b';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=OjzfQDFf7Uk' WHERE "id" = 'ppg6mc645921c33a365114282';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=gdE46YSedvE' WHERE "id" = 'ppg6m2727b74190c2f0e0799f';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=gdE46YSedvE' WHERE "id" = 'ppg6m6a9960090eee0e9a83d0';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=gSEYtAjuZ-Y' WHERE "id" = 'ppg6m148ea3e46108e96e1c49';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=k3aKKasOmIw' WHERE "id" = 'ppg6mae324e56b222c950f2e7';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=k3aKKasOmIw' WHERE "id" = 'ppg6m2c7aa57361785bf5b246';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=GdIkEngwGNU' WHERE "id" = 'ppg6m7a09f683820796530761';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=gSEYtAjuZ-Y' WHERE "id" = 'ppg6mccc067b760e93ac03bd3';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=b2C9I8HuCe4' WHERE "id" = 'ppg6mf003643af48a4daf1a56';
UPDATE "Lesson" SET "videoUrl" = 'https://www.youtube.com/watch?v=OjzfQDFf7Uk' WHERE "id" = 'ppg6m0ad31c7bb9247b85ff62';
