/**
 * Re-emit migrations/0004_grade6_core_content.sql from prisma/grade6-core.ts.
 * Run: npx tsx scripts/gen-grade6-content-sql.ts
 */
import { writeFileSync } from "node:fs";
import { allGrade6Authored } from "../prisma/grade6-core";

function esc(s: string) {
  return s.replace(/'/g, "''");
}

const lines: string[] = [
  "-- Grade 6 core lesson body upgrade (ELA, Math, Science, World History).",
  "-- Regenerated by scripts/gen-grade6-content-sql.ts — do not hand-edit long-term.",
  "-- Apply: npm run db:migrate:cloudflare   OR   wrangler d1 execute … --file this",
  "-- Do NOT run db:setup on production D1.",
  "",
];

for (const row of allGrade6Authored()) {
  const { id, lesson } = row;
  lines.push(
    `UPDATE "Lesson" SET "description" = '${esc(lesson.description)}', "objectives" = '${esc(lesson.objectives)}', "content" = '${esc(lesson.content)}' WHERE "id" = '${id}';`
  );
  lines.push("");
}

const out = "migrations/0004_grade6_core_content.sql";
writeFileSync(out, lines.join("\n"));
console.log(`Wrote ${out} (${allGrade6Authored().length} updates)`);
