/**
 * Emit core lesson content UPDATE fragment from prisma/grade6-core.ts.
 * (Does not overwrite applied migrations/0004_grade6_core_content.sql.)
 * Run: npx tsx scripts/gen-grade6-content-sql.ts
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { allGrade6Authored } from "../prisma/grade6-core";

function esc(s: string) {
  return s.replace(/'/g, "''");
}

const lines: string[] = [
  "-- Grade 6 core lessons: strip attribution / clean bodies. Generated by scripts/gen-grade6-content-sql.ts",
  "-- UPDATE content only. Do NOT run db:setup.",
  "",
];

for (const row of allGrade6Authored()) {
  const { id, lesson } = row;
  lines.push(
    `UPDATE "Lesson" SET "description" = '${esc(lesson.description)}', "objectives" = '${esc(lesson.objectives)}', "content" = '${esc(lesson.content)}' WHERE "id" = '${id}';`
  );
  lines.push("");
}

mkdirSync("scripts/generated", { recursive: true });
const out = "scripts/generated/_fragment_grade6_core_content_update.sql";
writeFileSync(out, lines.join("\n"));
console.log(`Wrote ${out} (${allGrade6Authored().length} updates)`);
